root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/aznetmon main.go"
bin = "./tmp/aznetmon"
include_ext = ["go", "tmpl", "html", "css", "js"]
exclude_dir = ["assets", "tmp", "vendor"]
delay = 1000
kill_delay = 500
stop_on_error = true

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = true