version: '3.8'

services:
  aznetmon:
    build: .
    ports:
      - "8080:8080"
    environment:
      # You can modify these targets or override with docker-compose up
      - ICMP_TARGETS=8.8.8.8,1.1.1.1,9.9.9.9,cloudflare.com,google.com
    restart: unless-stopped
    # Required for ICMP operations
    cap_add:
      - NET_RAW
    networks:
      - aznetmon

networks:
  aznetmon:
    driver: bridge
